version: 2.1



jobs:
  dockerfun:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            chmod 755 update.sh
            ./update.sh
            cat deployment.yml
            cat deployment2.yml





workflows:
  default:
    jobs:
      - dockerfun





